In [16]:
import pickle
import numpy as np

In [17]:
ohe_sex = pickle.load(open('models/ohe_sex.pkl', 'rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl', 'rb'))
clf = pickle.load(open('models/clf.pkl','rb'))

In [18]:
# ===============
# Assume user input 
# Pclass/gender/age/sibsp/Fare/Embarked

test_input = np.array([2,'male', 31.0, 0, 0, 10.5, 's'], dtype = object).reshape(1,7)

In [19]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 's']], dtype=object)

In [20]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

/opt/anaconda3/envs/jub/lib/python3.12/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [21]:
test_input_sex

array([[0., 1.]])

In [22]:
test_input_embarked = ohe_embarked.transform(test_input[:, -1].reshape(1,1))

In [24]:
test_input_embarked

array([[0., 0., 0.]])

In [25]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 's']], dtype=object)

In [28]:
test_input_age = test_input[:,2].reshape(1,1)

In [29]:
test_input_age

array([[31.0]], dtype=object)

In [30]:
test_input_transformed = np.concatenate((test_input[:, [0,3,4,5]], test_input_age, test_input_sex, test_input_embarked), axis = 1)

In [31]:
test_input_transformed.shape

(1, 10)

In [32]:
clf.predict(test_input_transformed)

array([1])